[project]
authors = ["Alex Nagorny <alex@swaygang.com>"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_contract"

[dependencies]
token_abi = { path = "../../abi/token_abi" }
# sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.4.1" }
