/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.27.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

export type { TokenAbi } from "./TokenAbi";

export { TokenAbi__factory } from "./factories/TokenAbi__factory";
