/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.26.0
  Forc version: 0.31.3
  Fuel-Core version: 0.14.0
*/

export type { TokenContractAbi } from "./TokenContractAbi";

export { TokenContractAbi__factory } from "./factories/TokenContractAbi__factory";
